---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret # For cookie sessions (not used anymore)
  MSG_KEY: <`rake generate:msg_key`>
  REDIS_URL: <provision Redis instance>
  IMAGE_BASE_URL: <images are hosted on IMAGE_BASE_URL/key>
  GO_OAUTH_URL: https://accounts.google.com/o/oauth2/auth
  GO_TOKEN_URL: https://oauth2.googleapis.com/token
  GO_SCOPE: user:email
  GO_CLIENT_ID: <Get Google OAuth client ID>
  GO_CLIENT_SECRET: <Get Google OAuth client secret>

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret # For cookie sessions (not used anymore)
  MSG_KEY: <`rake generate:msg_key`>
  REDIS_URL: <provision Redis instance>
  IMAGE_BASE_URL: <images are hosted on IMAGE_BASE_URL/key>
  GO_OAUTH_URL: https://accounts.google.com/o/oauth2/auth
  GO_TOKEN_URL: https://oauth2.googleapis.com/token
  GO_SCOPE: user:email
  GO_CLIENT_ID: <Get Google OAuth client ID>
  GO_CLIENT_SECRET: <Get Google OAuth client secret>

production:
  API_URL: <provisioned API URL (ending with api/[version])>
  APP_URL: <provisioned app URL (root without ending slash)>
  SESSION_SECRET: <`rake generate:session_secret`> # For cookie sessions (not used anymore)
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: <provision Redis instance>
  IMAGE_BASE_URL: <images are hosted on IMAGE_BASE_URL/key>
  GO_OAUTH_URL: https://accounts.google.com/o/oauth2/auth
  GO_TOKEN_URL: https://oauth2.googleapis.com/token
  GO_SCOPE: user:email
  GO_CLIENT_ID: <Get Google OAuth client ID>
  GO_CLIENT_SECRET: <Get Google OAuth client secret>